require 'asciidoctor'
require 'erb'

interactor :off
logger device: 'guard.log'

guard 'shell' do
  watch(/^Main\.adoc$/) {|m|
    Asciidoctor.convert_file(m[0], :in_place => true, safe: :unsafe)
    `cp Main.html /srv/ibooks.speechbubble.org.uk/UsingLowTechSymbolSystemsChildren/Main.html`
	`cp -r Media /srv/ibooks.speechbubble.org.uk/UsingLowTechSymbolSystemsChildren/`
  }
end