[bibliography]
[[aac]] AAC (Augmentative and Alternative Communication):: The term used to describe various methods of communication that can be used as an alternative or as an ‘add-on’ to speech where speech is not sufficient to enable successful communication in all situations all of the time. AAC includes simples systems such as pictures, gestures and pointing, as well as more complex techniques involving powerful computer technology.
[[access-method]] Access method:: Refers to the method by which an individual accesses their communication system. Also known as the selection method.
[[access-methods]] Access method:: Refers to the method by which an individual accesses their communication system. Also known as the selection method.
[[aided-aac]] Aided AAC:: Describes any type of AAC that uses some sort of equipment. Equipment to support communication could be simply a pencil and paper, or it could be a complex voice output communication aid.
[[automaticity]] Automaticity:: Describes motor activities that can be undertaken without much thought. For example, when first learning to drive, changing gear requires a lot of conscious thought. However,for an experienced driver, their body will just change the gear of the car without them having to think about what their foot is doing with the clutch or their hand is doing with the gear stick. Automaticity is acquired through repetition and practice.
[[unaided-aac]] Unaided AAC:: Describes AAC that does not make use of any equipment. Encompasses signing, gesture, vocalisation, etc.
[[alphabet-chart]] Alphabet chart:: An alphabet chart is a tool for communication. The alphabet is displayed so that an individual can select letters to support their face-to-face communication. It is a form of low tech AAC.
[[als]] ALS:: Amyotrophic Lateral Sclerosis (ALS) is also known as Lou Gehrig’s disease. It is more commonly called Motor Neurone Disease (MND) in the UK. It is a progressive neurodegenerative disease. The motor neurons degenerate and there is muscle wasting.
[[auditory-scanning]] Auditory Scanning:: An access method that is a form of listener mediated scanning. The options are read aloud and the individual indicates when they have heard the target option
[[basic-high-tech]] Basic high tech:: An alternative term for light tech communication.
[[cell]] Cell:: A defined shape on a symbol chart that contains a symbol and / or label. It is often square or rectangular in shape.
[[cerebral-palsy]] Cerebral palsy:: The name given to a number of conditions affecting the area of the brain controlling muscle movement that are acquired around the time of birth.
[[coded-access]] Coded access:: An access method where symbols are effectively given a grid reference that the individual then communicates. It requires two separate charts to communicate. One chart contains your symbols, the other allows you to communicate the location of the symbol you wish to communicate.
[[core]] Core vocabulary:: Words that are useful across lots of topics of conversation and are frequently used. For example, 'more', 'stop', 'help'. Core vocabulary is identified in empirical research or clinical reports that measure vocabulary use patterns across many individuals. Often used in contrast to term fringe vocabulary.
[[cortical-visual-impairment]] Cortical visual impairment:: A visual impairment that is related to the way the brain processes visual information rather than to the structure or function of the eye itself.
[[combination-access]] Combination access:: An access method that involves a combination of two or more standard access methods.
[[communication-partner]] Communication partner:: A communication partner is anyone that a person using AAC communicates with.
[[direct-selection]] Direct selection:: An access method where an individual makes a selection by touching it. Also known as direct touch.
[[direct-touch]] Direct touch:: An access method where an individual makes a selection by touching it. Also known as direct selection.
[[e-tran-frame]] E-tran frame:: An E-tran frame (or _eye-transfer frame_) is a low tech communication tool. It usually comprises a clear Perspex® frame to which symbols or letters are added, although it may be made of other materials such as laminate. There is often a central window or hole in the frame through which eye contact can be made. The frame is held up in front of the individual who then eye-points to the appropriate letter or symbol to communicate a message.
[[encoding]] Encoding:: Encoding describes the grouping of letters or symbols together to facilitate access. It is often associated with eye-pointing, but can also be used to facilitate direct access. It tends to be found in low tech communication systems.
[[eye-gaze]] Eye gaze:: Eye gaze systems can allow people with severe physical disabilities to access a communication aid or computer using their eyes. These devices have an inbuilt camera which tracks where you are looking and allows an individual to select something by blinking, dwelling (staring) or clicking a switch.
[[eye-pointing]] Eye pointing:: Eye pointing is an access method whereby an individual points with their eyes to a letter, word, symbol or object to communicate a message.
[[eye-transfer-frame]] Eye-transfer frame:: An eye-transfer frame (or e-tran frame) is a low tech communication tool. It usually comprises a clear Perspex® frame to which symbols or letters are added, although it may be made of other materials such as laminate. There is often a central window or hole in the frame through which eye contact can be made. The frame is held up in front of the individual who then eye-points to the appropriate letter or symbol to communicate a message.
[[eyelink]] EyeLink:: A communication chart where letters are printed or placed on a transparent material. This is held up between an individual and their communication partner, and the individual looks directly at the letter they wish to communicate. The communication partner moves the chart until they are looking at the same letter, and speaks aloud the letter to confirm the selection.
[[facilitated-communication]] Facilitated communication (FC):: “...or Facilitated Communication Training (FCT) as described by Rosemary Crossley who is credited with being the originator, is a technique in which physical, communication, and emotional support is provided by a facilitator to an individual with a communication disorder (communicator). With assistance, the communicator points to symbols such as letters, pictures and/or objects.” American Speech- Language Hearing Association (ASHA)
[[fitzgerald-key]] Fitzgerald key:: Developed by Edith Fitzgerald in the 1920s to help teach grammar to individuals with a hearing impairment.  The key assigns a colour to different parts of speech.  The modified Fitzgerald Key has been used in the AAC community to highlight the grammatical function of a symbol e.g. verb (green), noun (orange), adjective (blue), etc.
[[fringe]] Fringe:: Vocabulary that is specific to an individual, or to a certain topic of conversation or situation. Often used in contrast to the term core vocabulary.
[[high-tech-communication]] High tech communication:: High tech refers to a communication system that involves a battery or is computerbased. The term is often used in contrast to low tech communication. It is a form of Augmentative and Alternative Communication (AAC).
[[keyguard]] Keyguard:: A cover that fits over a keyboard or computer screen that contains holes through which keys or areas of the screen can be selected. It is designed to help with direct touch.
[[laser-pointer]] Laser pointer:: A small piece of equipment that is used to highlight an item using a narrow laser beam.
[[light-tech-communication]] Light tech communication:: Light tech refers to a simple communication system that involves a battery, and is a form of Augmentative and Alternative Communication (AAC). Light tech devices tend to make use of pre-recorded speech, rather than a synthesised voice. Light tech communication is sometimes subsumed within the label High tech communication.
[[listener-mediated-scanning]] Listener mediated scanning:: This is an access method whereby the communication partner delivers the options available to an individual. The individual then indicates when they have seen and / or heard the desired option, thereby communicating a message. The options may be delivered by speech alone (auditory scanning), by simply pointing the options available (visual scanning) or by speaking aloud the options whilst pointing to them (visual and auditory scanning). Also known as partner assisted scanning.
[[low-tech-communication]] Low Tech Communication:: A communication system that does not require a battery. This includes tools such as a paper alphabet chart , a symbol chart or book, an E-tran frame, pen and paper, etc. It is a form of augmentative and alternative communication (AAC). The term may be
used in contrast to high tech communication.
[[motor-neurone-disease]] Motor Neurone Disease:: Motor Neurone Disease (MND) is a progressive neurodegenerative disease. The motor neurones degenerate and there is muscle wasting. It is also known as Amyotrophic Lateral Sclerosis (ALS) and Lou Gehrig’s disease.
[[no-fail-activities]] No fail activities:: Describes games and activities where there is no obviously 'wrong' answer.
[[objects-of-reference]] Objects of reference:: A form of Low tech AAC.  Objects of reference are objects or things that are used to represent concepts e.g. a plastic cup might be used to represent the concept of having a drink.  Objects of reference may be used to help someone remember something, to help them understand something, or to help them anticipate something that is going to happen.   An object of reference may also be used by an individual to express themselves.
[[partner-assisted-scanning]] Partner assisted scanning:: This is an access method whereby the communication partner delivers the options available to an individual. The individual then indicates when they have seen and / or heard the desired option, thereby communicating a message. The options may be delivered by speech alone (auditory scanning), by simply pointing the options available (visual scanning) or by speaking aloud the options whilst pointing to them (_visual and auditory scanning_). Also known as listener mediated scanning.
[[pecs]] PECS:: PECS or Picture Exchange Communication System is a scheme which teaches people on the autistic spectrum the purpose of communication by requiring them to physically exchange a symbol with a communication partner. http://www.pecs-unitedkingdom.com/
[[point-taking]] Point-talking:: Also known as modelling or aided language stimulation. The communication partner points to symbols whilst talking to the person who uses AAC. The communication partner is demonstrating how to use the communication system.
[[pointing-tool]] Pointing tool:: These are tools designed to help people with a disability to point or select keys on a keyboard more accurately. Also known as a typing aid, a keyboard aid, a touch enabling device, a dibber, a universal cuff and more!
[[pre-recorded-speech]] Pre-recorded speech:: Also known as digitised speech. Speech that is recorded in advance for use on a light or high tech communication aid. Usually recorded directly onto a device using a built in microphone ba a communication partner.
[[selection-method]] Selection method:: Refers to the method by which an individual accesses their communication system. Also known as the access method.
[[signing]] Signing:: Signing is a method of communication that uses recognised hand and body gestures.
[[smart-partner]] Smart Partner:: A smart partner is a communication partner who is able to adapt to the environment or the needs of the individual and modify their behaviour or expectations of behaviour from a person using AAC accordingly. For example, a smart partner might know that an individual using AAC is unwell and realise that the way they communicate ‘yes‘ might be affected. The term is often used in contrast to a computer based communication system which is not able to adapt to the environment in the same way.
[[switch]] Switch:: A switch is a button that can be pressed to enable someone with a physical disability to access a wide range of technology, from a simple light or fan through to a voice output communication aid or computer. They come in a wide variety of sizes and designs and can be accessed using different body parts. In order to control the technology, a switch interface of some sort is sometimes required.
[[symbol-chart]] Symbol chart:: A communication chart made using symbols or pictures.
[[symbols]] Symbols:: Special pictures that are used to represent concepts e.g. a drawing of a person drinking out of a cup is used to represent the concept of having a drink. They are used both to support understanding and to help someone express themselves.
[[symbol-set]] Symbol set:: A group of pictorial symbols with a common design theme. There are a number of different symbol sets available.
[[synthesised-speech]] Synthesised speech:: The artificial production of human speech by a computer or communication aid. This is usually done via text to speech (TTS) software. A variety of voices are available from different suppliers.
[[talking-button]] Talking button:: This is an informal name for a voice output communication aid which can deliver a single pre-recorded message. They come in a variety of shapes and sizes, but are usually operated by pressing a button.
[[tangible-symbols]] Tangible symbols:: Tangible symbols are symbols that can be felt with the hands or body.  Sometimes used as another word for objects of reference.  Also used to describe more abstract symbols created using different shapes and textures.  In the latter context, also known as tactile symbols.
[[text-based-low-tech-aac]] Text based low tech AAC:: A form of low tech Augmentative and Alternative Communication (AAC) that is made using words and / or individual letters.
[[visual-and-auditory-scanning]] Visual and auditory scanning:: An access method that is a form of listener mediated scanning. The communication partner points to the options whilst reading them aloud, and the individual indicates when they have seen and heard the target option.
[[visual-scanning]] Visual scanning:: An access method that is a form of listener mediated scanning. The communication partner points to the options available, and the individual indicates when the communication partner is pointing to the target option.
[[voice-output-communication-aid]] Voice output communication aid:: See AAC.
[[writing-slope]] Writing slope:: A piece of equipment designed to help someone write on paper at an optimum angle.
[[zyfuse-heater]] Zyfuse heater:: This equipment is a little like a printer.  When used with Zytex2 paper, it can produce tactile diagrams.  The Zyfuse Heater causes the ink on the special paper to swell, resulting in a raised diagram.
